fix: update utcnow for python 3.12 deprecation
bobbui/json-logging-python pull request #107
Opened 2024-07-14 20:55 UTC by donbowman

In python3.12 we get deprecation errors due to the use of 'naive' timestamps
from utcnow. (see https://github.com/python/cpython/issues/103857)

Replace with timezone.utc

See  https://github.com/python/cpython/issues/81669 

See https://blog.miguelgrinberg.com/post/it-s-time-for-a-change-datetime-utcnow-is-now-deprecated

2024-10-03 18:35 UTC, csueiras approved these changes

2025-04-28 17:02 UTC, dwt commented
I don't quite get why the `.replace(tzinfo=None)` is there? It would seem that timezone aware date times should be just as well to compute the total seconds. Other than that, this looks like it should solve the issue.

2025-04-28 17:04 UTC, dwt commented
@bobbui Is there anything I can do to make this more mergeable? Sadly the last run here is so long ago that the logs are not accessible anymore, so I'm not sure what the problem is.

But this is slowly becoming pressing as we want to update to python 3.14 soon.

2025-04-28 17:08 UTC, donbowman commented
i can remove the replace(tzinfo=None).
The only failure is for py3.7, which IMHO you would remove as it was EOL in 2023.

2025-04-28 17:43 UTC, donbowman commented
i have made a few minor changes to the test environment in this PR:
- remove python3.7
- pin sanic
- update flake8 issues (flake8 is not pinned, neither is pytest)

now all the tests pass at this instance in time.

2025-04-28 18:51 UTC, dwt requested changes
Small niggles, but definitely nice work!

2025-04-28 18:51 UTC, dwt commented on .github/workflows/code_quality.yml
> +        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
3.8 is also already eol, but 3.13 is out, so that would be good to add

2025-04-28 18:51 UTC, dwt commented on json_logging/formatters.py
> +        utcnow = datetime.now(timezone.utc).replace(tzinfo=None)
You may have missed this one, I think the `replace()` needs to go here too.

2025-04-28 19:03 UTC, dwt approved these changes
LGTM

2025-04-29 14:12 UTC, dwt commented
I'm using it enough so I wouldn't mind to be a co maintainer, but I would mostly provide review and feedback, as I am very much focused on nix and nixos in my open source time right now.

2025-05-03 18:35 UTC, dwt commented
Friendly ping to @bobbui Could you please take a look at this issue and help us get this merged?

2025-05-16 13:58 UTC, dwt commented
Another friendly ping to @bobbui - this issue is getting more and more pressing as the package is incompatible with python 3.12, while python 3.14 is getting released any day now.

2025-05-29 17:56 UTC, dwt commented
Friendly Ping to @bobbui - could you please take a look at this - as far as I can see the fix is included.

We would really like to use your library on newer python versions.

2025-06-30 12:19 UTC, dwt commented
Friendly ping at @bobbui Can you give a timeframe when you will be able to look at this?

2025-07-01 20:30 UTC, bobbui commented
sorry, been really busy with family

2025-07-01 20:31 UTC, merged

2025-07-05 18:34 UTC, dwt commented
@bobbui, I had a Quick Look, and was a bit confused, I'll write something to the developer

2025-07-05 18:36 UTC, dwt commented
@bobbui Do you already have a release schedule for this fix? We would like to upgrade our deployments and are running into this problem.